### ISSUE TITLE
Issue on Page Reload

### ISSUE THREAD

**Issue by bikathi** [RollingTL/Image-gallery-nuxt3-i18n#1]
Hey. I am actually basing my i18n stuff on a client project off of your work. I cloned this repo and had it installed properly. When I run it in a browser I am able to switch between the languages easily. Problem comes when I reload the page after changing to one of the three languages. 
I get this infamous error:
![Screenshot_25-4-2024_93256_localhost](https://github.com/RollingTL/Image-gallery-nuxt3-i18n/assets/98804363/072e15d8-98fb-42c6-89f8-5fe6947d9fee)

I would like to know what causes this and whether I'll get the same issue when I start working on i18n in my already large project. 
To fix it, I actually have to go to the dev tools and delete the cookie stored by the lang preference then restart the Nuxt app. Not a viable thing to do in production.

**Comment by RollingTL** [comment]
You possibly made some changes in routes or locales while developing that causes your problem. Normally in dev mode all works ok - change language - refresh. 
If you clear all cookies and check change lang and refresh and it works than in production you will have no problems. 

If you can give steps to reproduce your issue I could give more detailed answer. I saw that once when changing branches - fixed by clearing cookie and restarting VScode and dev server.

**Comment by bikathi** [comment]
Ok, so I didn't really do much in terms of touching your code. I just cloned it, `npm install` and `npm run dev`. Up to this point i had not opened up the code in any text editor. After running the code for the first time is when I noticed this issue and started reading through the code.

Here is my coding environment:
Editor: VSCode
Browser: Edge
OS: Ubuntu Linux 23.10 (Kubuntu)
Node Version: 20.10

**Comment by RollingTL** [comment]
I have repeat the process again - didn't see errors.
